# Generated by Django 4.2 on 2023-05-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forum_topic_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_suspension',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
