# Generated by Django 4.2 on 2023-05-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.user'),
            preserve_default=False,
        ),
    ]
