# Generated by Django 4.2 on 2023-05-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_session_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='email',
            new_name='user',
        ),
    ]
