# Generated by Django 4.2 on 2023-06-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_rename_email_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
