# Generated by Django 4.2 on 2023-06-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_topic_post_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
