# Generated by Django 4.2 on 2023-06-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_alter_post_date_created_alter_user_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
