# Generated by Django 4.2.1 on 2023-05-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateData",
            fields=[
                (
                    "id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=30)),
                ("content", models.TextField()),
            ],
        ),
    ]
