# Generated by Django 4.2 on 2023-06-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_firstaidcase_firstaidstep_delete_templatedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('word', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('synonym', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.keywords')),
            ],
        ),
        migrations.CreateModel(
            name='Assoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_count', models.IntegerField()),
                ('view_count', models.IntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.firstaidcase')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.keywords')),
            ],
        ),
    ]
