# Generated by Django 4.2 on 2023-06-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_alter_assoc_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assoc',
            name='view_count',
        ),
    ]
