# Generated by Django 4.2 on 2023-06-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0006_remove_assoc_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidcase',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
