# Generated by Django 4.2.1 on 2023-05-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_general', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_general',
            new_name='User',
        ),
    ]
